name: Repo-Tranporter-1

on:
  schedule:
    - cron:  '*/5 * * * *'
# 就当我改动了
jobs:
  transport:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    # 获取原仓库的版本
    - name: Get Latest HLAE Tag
      # ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
      uses: actions-hub/watch-tag@master
      with:
         provider: github
         repository: advancedfx/advancedfx
         env_name: LATEST_HLAE_TAG
    
    # 获取当前仓库的版本
    - name: Get Latest HLAE-Release Tag
      # ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
      uses: actions-hub/watch-tag@master
      with:
         provider: github
         repository: yellowfisherz/HLAE-Release
         env_name: THIS_TAG
    
    # 运行工具
    - if: env.THIS_TAG != env.LATEST_HLAE_TAG
      name: Run Repo-Tranporter
      run: |
        ls -al
        chmod 777 repo-transporter
        ./repo-transporter
    
    - if: env.THIS_TAG != env.LATEST_HLAE_TAG
      name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4.4.0
      with:
        # Commit message
        commit_message: "Git Auto Commit"
    
    - name: Test Files 
      run : ls -al
    
    # Push 上传
    - if: env.THIS_TAG != env.LATEST_HLAE_TAG
      uses: ad-m/github-push-action@v0.6.0
      with:
        # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
        github_token: $\{{ secrets.GITHUB_TOKEN }}

        
    # Release 发布
    - if: env.THIS_TAG != env.LATEST_HLAE_TAG
      name: Create a Release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: 'v${{ env.LATEST_HLAE_TAG }}'
      with:
       tag_name: ${{ env.TAG }}
       release_name: ${{ env.TAG }}
       body: This release is automatically made by GitHub Actions
       draft: false
       prerelease: false
